### ISSUE TITLE
hcitool and gatttool deprecated

### ISSUE THREAD

**Issue by beaufortfrancois** [poshaughnessy/over-the-air-2016-bluetooth#2]
For info, BlueZ `hcitool` and `gatttool` are deprecated. You may want to use `bluetoothctl` or any newer tooling such as `btmgmt` included in newer releases of BlueZ.

**Comment by poshaughnessy** [comment]
Ah, good to know. I will add a note to the slides and update it next time - thanks!

**Comment by poshaughnessy** [comment]
Added warning note df0c464f3be94b9bb5a63114c86bda2d7dea499c
